### PR TITLE
Changed conversion of types in RoleStore: FindByIdAsync(string)

### PR DESCRIPTION
**Pull request by steine**
Tested in another branch where I had to convert all projects to the new format and what not.

### CODE REVIEW

**Comment by grandchamp** [comment]
Did you tested with other types other than GUID?

**Comment by steine** [comment]
Only tested with Guid.
I had to convert the whole thing to the new core format to just get it running (VS mac) and could only test in my own environment, the version of moq that was included did not work on the latests core either.

Do you have a good idea on how we can strengthen the testing, haven't really worked with any mocking before.

But the implementation is shamelessly stolen directly from how ASP.Net Core Identity converts to all their keys.

**Comment by grandchamp** [comment]
I'll merge in the .NET Core 2.0 branch and test before merging in master. You can do changes there too, i think it'll be easier since you are working on VS for MAC.

**Comment by grandchamp** [comment]
And about tests, i've created an issue. #36

**Pull request merged**
